version: "3.7"

volumes:
  db_data:
  pgadmin-data:

networks:
  backend:
  server:
  database:

services:
  &node resume-prototype-node:
    hostname: *node
    container_name: *node
    image: node:16-alpine3.11
    working_dir: /var/www/resume-prototype
    volumes:
      - ./www:/var/www/resume-prototype

  &database resume-prototype-mysql:
    hostname: *database
    container_name: *database
    image: mysql:8
    environment: 
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: unless-stopped
    volumes: 
      - db_data:/var/lib/mysql
    networks: 
      - backend
      - database
      
  &phpmyadmin resume-prototype-phpmyadmin:
    hostname: *phpmyadmin
    container_name: *phpmyadmin
    environment: 
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PMA_HOST: *database
    image: phpmyadmin:5.1.1
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - *database
    networks: 
      - database

  &php-fpm resume-prototype-php-fpm:
    hostname: *php-fpm
    container_name: *php-fpm
    build: 
      context: docker/php-fpm
      args: 
        DEFAULT_USER_ID: ${DEFAULT_USER_ID}
        DEFAULT_GROUP_ID: ${DEFAULT_GROUP_ID}
        DEFAULT_USER: ${DEFAULT_USER}
        DEFAULT_GROUP: ${DEFAULT_GROUP}
    volumes:
      - ./www:/var/www/resume-prototype
      - ./docker/php-fpm/uploads.ini:/usr/local/var/php/conf.d/custom.ini
      - ./docker/php-fpm/www.conf:/usr/local/var/php-fpm.d/www.conf
    depends_on:
      - *database
    networks: 
      - backend
      - server

  &web-server resume-prototype-nginx:
    hostname: *web-server
    container_name: *web-server
    build: docker/nginx
    environment: 
      FPM_PORT: ${FPM_PORT}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www/resume-prototype
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - *php-fpm
    networks: 
      - server